export const appShellCopy = {
  title: '书签清理与归档工作区',
  subtitle: '当前阶段先冻结扩展壳和页面入口，后续任务再接入草稿图谱与同步能力。',
  topShellLabel: '顶部动作区',
  searchLabel: '搜索与聚焦区',
  canvasLabel: '图谱画布区',
  hintLabel: '操作提示区',
  statusLabel: '状态结果区',
  searchPlaceholder: '后续任务会在这里接入标题或 URL 搜索',
  canvasPlaceholder: '图谱工作区入口已建立，后续任务将在这里挂接草稿图谱和节点交互。',
  statusPlaceholder: '结果历史区入口已保留；当前壳阶段不产生真实动作记录。',
  actionLabels: [
    '从浏览器覆盖当前草稿',
    '同步当前草稿到浏览器书签',
    '上传当前草稿到 WebDAV',
    '上传当前浏览器书签到 WebDAV',
    '恢复 WebDAV 草稿到当前草稿',
    '恢复 WebDAV 书签到浏览器书签',
    '撤销覆盖操作',
  ],
  secondaryLabels: ['重新整理布局', 'WebDAV 设置'],
  hintItems: [
    '单击：选择节点',
    '双击：编辑节点',
    '拖拽：移动节点',
    'Enter：创建子节点',
    'Delete / Backspace：删除节点',
    'Ctrl+Z：撤销一次草稿编辑',
  ],
} as const;
